apiVersion: v1
kind: Service
metadata:
  name: barramento-de-eventos-service
spec:
  type: ClusterIP
  selector:
    app: barramento-de-eventos
  ports:
    - name: barramento-de-eventos
      protocol: TCP
      port: 10000
      targetPort: 10000