apiVersion: v1
kind: Service
metadata:
  name: classificacao-service
spec:
  selector:
    app: classificacao
  type: ClusterIP
  ports:
    - name: classificacao
      protocol: TCP
      port: 7000
      targetPort: 7000

--- 
apiVersion: v1
kind: Service
metadata:
    name: classificacao-service-node-port
spec:
  type: NodePort
  selector:
    app: classificacao
  ports: 
    - name: classificacao
      protocol: TCP
      port: 7000
      targetPort: 7000