apiVersion: v1
kind: Service
metadata:
  name: consulta-service
spec:
  selector:
    app: consulta
  type: ClusterIP
  ports:
    - name: consulta
      protocol: TCP
      port: 6000
      targetPort: 6000

--- 
apiVersion: v1
kind: Service
metadata:
    name: consulta-service-node-port
spec:
  type: NodePort
  selector:
    app: consulta
  ports: 
    - name: consulta
      protocol: TCP
      port: 6000
      targetPort: 6000