apiVersion: apps/v1
kind: Deployment
metadata:
  name: lembretes-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lembretes
  template:
    metadata:
      labels:
        app: lembretes
    spec:
      containers:
        - name: lembretes
          image: cadudias/lembretes:latest
          ports: 
            - containerPort: 4000
          resources:
            limits:
              memory: 256Mi
              cpu: 1
