apiVersion: v1
kind: Service
metadata:
  name: lembretes-service
spec:
  type: ClusterIP
  selector:
    app: lembretes
  ports:
    - name: lembretes
      protocol: TCP
      port: 4000
      targetPort: 4000

---
apiVersion: v1
kind: Service
metadata:
    name: lembretes-service-node-port
spec:
  type: NodePort
  selector:
    app: lembretes
  ports: 
    - name: lembretes
      protocol: TCP
      port: 4000
      targetPort: 4000