apiVersion: apps/v1
kind: Deployment
metadata:
  name: logs-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logs
  template:
    metadata:
      labels:
        app: logs
    spec:
      containers:
        - name: logs
          image: cadudias/logs:latest
          ports:
            - containerPort: 8000
          resources:
            limits:
              cpu: 1
              memory: 256Mi