apiVersion: v1
kind: Service
metadata:
  name: logs-service
spec:
  selector:
    app: logs
  type: ClusterIP
  ports:
    - name: logs
      protocol: TCP
      port: 8000
      targetPort: 8000

--- 
apiVersion: v1
kind: Service
metadata:
    name: logs-service-node-port
spec:
  type: NodePort
  selector:
    app: logs
  ports: 
    - name: logs
      protocol: TCP
      port: 8000
      targetPort: 8000