apiVersion: v1
kind: Service
metadata:
  name: observacoes-service
spec:
  selector:
    app: observacoes
  type: ClusterIP
  ports:
    - name: observacoes
      protocol: TCP
      port: 5000
      targetPort: 5000

--- 
apiVersion: v1
kind: Service
metadata:
    name: observacoes-service-node-port
spec:
  type: NodePort
  selector:
    app: observacoes
  ports: 
    - name: observacoes
      protocol: TCP
      port: 5000
      targetPort: 5000